# Generated by Django 4.2.2 on 2023-06-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(default='Descripcion', max_length=500)),
                ('anno_lanzamiento', models.CharField(default='0', max_length=4)),
                ('clasificacion', models.CharField(default='', max_length=2)),
                ('desarrollador', models.CharField(default='', max_length=50)),
                ('genero', models.CharField(default='', max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
