# Generated by Django 4.2.2 on 2023-06-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_video',
            field=models.CharField(default='', max_length=30),
        ),
    ]
