# Generated by Django 4.2.2 on 2023-06-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0002_producto_id_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='tiendaweb_producto',
        ),
    ]
