# Generated by Django 4.2.2 on 2023-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tiendaweb_cliente',
            },
        ),
    ]
