# Generated by Django 4.2.2 on 2023-06-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('cant_productos', models.IntegerField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaweb.cliente')),
            ],
            options={
                'db_table': 'tiendaweb_boleta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=500)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaweb.boleta')),
            ],
            options={
                'db_table': 'tiendaweb_detalle_boleta',
            },
        ),
    ]
