# Generated by Django 4.2.2 on 2023-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0005_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cant_productos',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
