# Generated by Django 4.2.2 on 2023-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0006_alter_boleta_cant_productos_alter_boleta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='precio',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
