# Generated by Django 4.2.2 on 2023-06-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0007_detalle_boleta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='precio',
        ),
    ]
