# Generated by Django 4.2.2 on 2024-05-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0009_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.CharField(default='--/--/--_--:--:--', max_length=30),
        ),
        migrations.AddField(
            model_name='boleta',
            name='nro_orden',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='boleta',
            name='tipo_pago',
            field=models.CharField(default='', max_length=30),
        ),
    ]
