# Generated by Django 4.2.2 on 2024-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaweb', '0011_cliente_groups_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
